### ISSUE TITLE
使用正点原子IMX6ULLmini开发板，刷了这个固件，sysupgrade和网页升级都失败了

### ISSUE THREAD

**Issue by ynkan** [boxwoodt/imx6ull_openwrt#1]
### Describe the bug

您好，我是用这个固件测试了一下，发现了以下几个问题
1. 上电以后默认随机MAC地址，每次都要重新查找IP
2. 网页升级不能成功
3. 系统命令升级也不能成功，日志如下
sysupgrade -n -v openwrt-imx-cortexa7-imx6ull-atk-emmc-squashfs-sysupgrade.bin 
Mon May 20 04:15:14 UTC 2024 upgrade: Commencing upgrade. Closing all shell sessions.
Command failed: Connection failed
[ 1935.183371] stage2 (4226): drop_caches: 3
[ 1944.640752] ci_hdrc ci_hdrc.1: remove, state 4
[ 1944.645499] usb usb1: USB disconnect, device number 1
[ 1944.653006] ci_hdrc ci_hdrc.1: USB bus 1 deregistered
[ 1944.674281] imx2-wdt 20bc000.watchdog: Device shutdown: Expect reboot!
[ 1944.680983] reboot: Restarting system

### OpenWrt version

r0+23781-0844937947

### OpenWrt target/subtarget

imx/cortexa7

### Device

Freescale ATK IMX6ULL Board

### Image kind

Official downloaded image

### Steps to reproduce

1. 上电以后默认随机MAC地址，每次都要重新查找IP
2. 网页升级不能成功
3. 系统命令升级也不能成功，日志如下
sysupgrade -n -v openwrt-imx-cortexa7-imx6ull-atk-emmc-squashfs-sysupgrade.bin 
Mon May 20 04:15:14 UTC 2024 upgrade: Commencing upgrade. Closing all shell sessions.
Command failed: Connection failed
[ 1935.183371] stage2 (4226): drop_caches: 3
[ 1944.640752] ci_hdrc ci_hdrc.1: remove, state 4
[ 1944.645499] usb usb1: USB disconnect, device number 1
[ 1944.653006] ci_hdrc ci_hdrc.1: USB bus 1 deregistered
[ 1944.674281] imx2-wdt 20bc000.watchdog: Device shutdown: Expect reboot!
[ 1944.680983] reboot: Restarting system

### Actual behaviour

.

### Expected behaviour

.

### Additional info

.

### Diffconfig

```text
.
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by boxwoodt** [comment]
1、 `u-boot -2022`中默认`mac` 地址为随机生成，可以在`u-boot`中通过以下指令进行配置，保存在环境变量中。

```
setenv ethaddr 32:43:a0:63:17:7b
setenv eth1addr ae:62:ba:c5:6c:1c
saveenv
```

2、目前只在 i.MX6ULL Linux阿尔法开发板上验证过，Mini Linux开发板没有测试过。可以通过以下两个固件交叉升级验证是否升级成功，两个固件的luci主题不同。
https://note.youdao.com/ynoteshare/index.html?id=6e1b5310667b3b50ed65f58e89dfdeb0&type=note&_time=1716222268275

https://note.youdao.com/ynoteshare/index.html?id=cf91ae5625e0d0a28c8bf81f3917f48c&type=note&_time=1716222367062

**Comment by ynkan** [comment]
您好，你试过在shell界面通过命令升级吗，方便贴个那个日志信息不？按理正点原子的这个开发板核心板一样，不会出现这种问题的才对

**Comment by ynkan** [comment]
我试了这两个固件，还是一样的结果，shell界面命令行升级提示如下：
-------------------------------------------------------------------------------------
sysupgrade -n -v /root/openwrt-23.05-snapshot-r23789-f7c771329e-imx-cortexa7-imx6ull-atk-emmc-squas.bin 
Tue May 21 14:52:15 UTC 2024 upgrade: Image not in /tmp, copying...
Tue May 21 14:52:16 UTC 2024 upgrade: Commencing upgrade. Closing all shell sessions.
Command failed: Connection failed
[  581.741545] stage2 (3206): drop_caches: 3
[  590.795111] ci_hdrc ci_hdrc.1: remove, state 4
[  590.799852] usb usb1: USB disconnect, device number 1
[  590.807493] ci_hdrc ci_hdrc.1: USB bus 1 deregistered
[  590.827730] imx2-wdt 20bc000.watchdog: Device shutdown: Expect reboot!
[  590.834428] reboot: Restarting system
-------------------------------------------------------------------------------------
我追查过这个 "Command failed: Connection failed",是sysupgrade命令在调用ubus call sysupgrade 的时候出的错，暂时还不知道原因。

**Comment by boxwoodt** [comment]
可能和板子有关，阿尔法开发板上没有`Command failed: Connection failed`。这个是我阿尔法升级的部分日志。

```
root@OpenWrt:~# ls
openwrt-23.05-snapshot-r23789-f7c771329e-imx-cortexa7-imx6ull-atk-emmc-squashfs-sysupgrade.bin
root@OpenWrt:~# sysupgrade -n -v openwrt-23.05-snapshot-r23789-f7c771329e-imx-co
rtexa7-imx6ull-atk-emmc-squashfs-sysupgrade.bin
Tue May 21 15:35:50 UTC 2024 upgrade: Image not in /tmp, copying...
Tue May 21 15:35:52 UTC 2024 upgrade: Commencing upgrade. Closing all shell sessions.
[  543.845959] stage2 (4521): drop_caches: 3
[  551.169956] EXT4-fs (mmcblk0p1): mounted filesystem without journal. Opts: (null). Quota mode: disabled.
[  553.887563] ci_hdrc ci_hdrc.1: remove, state 1
[  553.892261] usb usb1: USB disconnect, device number 1
[  553.897377] usb 1-1: USB disconnect, device number 2
[  553.902435] usb 1-1.4: USB disconnect, device number 4
[  553.907970] rndis_host 1-1.4:1.0 usb0: unregister 'rndis_host' usb-ci_hdrc.1-1.4, RNDIS device
[  553.930633] option1 ttyUSB0: GSM modem (1-port) converter now disconnected from ttyUSB0
[  553.938873] option 1-1.4:1.2: device disconnected
[  553.944888] option1 ttyUSB1: GSM modem (1-port) converter now disconnected from ttyUSB1
[  553.953217] option 1-1.4:1.3: device disconnected
[  553.959100] option1 ttyUSB2: GSM modem (1-port) converter now disconnected from ttyUSB2
[  553.967322] option 1-1.4:1.4: device disconnected
[  553.973175] option1 ttyUSB3: GSM modem (1-port) converter now disconnected from ttyUSB3
[  553.981467] option 1-1.4:1.5: device disconnected
[  553.992064] ci_hdrc ci_hdrc.1: USB bus 1 deregistered
[  554.002579] imx2-wdt 20bc000.watchdog: Device shutdown: Expect reboot!
[  554.009468] reboot: Restarting system
```

**Comment by ynkan** [comment]
我换了一个核心板确实是可以的，升级我自己的也能成功，奇了怪了。这个问题应该和核心板没啥关系才对啊

**Comment by ynkan** [comment]
大概定位到问题了，是SD卡的锅。我换回之前测试的SD卡就是不行，暂时还不知道什么原因
